site_name: Fosscord Docs
repo_url: https://github.com/fosscord/fosscord
edit_uri: https://github.com/fosscord/fosscord-docs/edit/master/docs/
site_description: Documentation of Fosscord a free open source selfhostable chat, voice and video discord-compatible platform
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  font: Open Sans
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
plugins:
  - section-index
  - search
  - render_swagger
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en